POST http://localhost:5000/users/register
Content-Type: application/json

{
    "user": {
        "firstName": "Elon",
        "lastName": "Musk",
        "email": "musk@spacex.com",
        "password": "123456"
    }
}

###

GET http://localhost:5000/users/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMzM2JkMTMwZDk5YTYyNWY2MTU3MGQiLCJpYXQiOjE2NTY5NjIwMDF9.dgQ5dkIKVxwz0RuH6WLx5BjCIfYTk3bWqIqcPCrodk0

###

POST http://localhost:5000/payment/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0MGQ4ZGFjMDIyNGY1OGMyMDgwMWMiLCJ1c2VyU3Vic2NyaXB0aW9uVG9rZW4iOiJzb21lLnJhbmRvbS5zdHJpbmcubGlrZS5qd3QiLCJpYXQiOjE2NTcwMTU2OTMsImV4cCI6MTY1NzAxNjI5M30.z0vtUqJ42JDULHlvBM7XAyDC1t5t82hJdkxyxuyCJCs