POST http://localhost:5000/users/login
Content-Type: application/json

{
    "user": {
        "firstName": "Server",
        "lastName": "Admin",
        "email": "admin@nakratko.com",
        "password": "123456",
        "roleKey": "0000"
    }
}

###

GET http://localhost:5000/users/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMzMDljMDM0ZWY0Mjg2ZDMxOTM4MmQiLCJpYXQiOjE2NTY5NDkxODR9.2le_0WI7MInz9Wz13haPiMqQQvqG-ROOBGuqbtFE0Us

###

GET http://localhost:5000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMzMDljMDM0ZWY0Mjg2ZDMxOTM4MmQiLCJpYXQiOjE2NTY5NTg1NDcsImV4cCI6MTY1Njk1ODU1N30.xz0YyaGY4ir7ygTA-XyQRkejj_icEzBNPO3kS2jRwac