POST http://localhost:5000/users/login
Content-Type: application/json

{
    "user": {
        "firstName": "Server",
        "lastName": "Admin",
        "email": "admin@nakratko.co",
        "password": "123456",
        "roleKey": "0000"
    }
}

###

GET http://localhost:5000/users/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmMzM2JkMTMwZDk5YTYyNWY2MTU3MGQiLCJpYXQiOjE2NTY5NjIwMDF9.dgQ5dkIKVxwz0RuH6WLx5BjCIfYTk3bWqIqcPCrodk0

###

POST http://localhost:5000/payment/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0NzA3NTIyMTU3Mzg5YTE0NjgwMzEiLCJpYXQiOjE2NTcwNDE2NzMsImV4cCI6MTY1NzA0MjI3M30.eKRWdCWZpXcSZD5axYYCUKiSNcCpuy7v-dljdfkZHMw

###

GET http://localhost:5000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0ODA2ZTcxMzAyYjQ1YTE0Y2YwODAiLCJpYXQiOjE2NTcwNDUxMDIsImV4cCI6MTY1NzA0NTcwMn0.T_lKpCKrmT_RNCI4bxI2xq8_NAirTe_8VXs1gqnPHb4

###

GET http://localhost:5000